### ISSUE TITLE
timesketch_api_client error while save credential

### ISSUE THREAD

**Issue by knsankar** [log2timeline/dftimewolf#276] opened 2020-05-15 18:15 UTC
Hi,
I pulled latest update (_4159e3bb97e22c1b630f3d717a12f4887693534d_) and tried to run _plaso_ts_, _grr_artifact_ts_ and it was asking for credentials to create timesketchrc. After provided the uri, user, password, I am getting following error.

Configuration loaded from: /opt/dftimewolf/data/config.json
Loading recipe...
Loaded recipe plaso_ts with 3 modules
Running preflights...
Setting up modules...
[WARNING] No timesketch section in the config
What is the value for [auth_mode]: timesketch
What is the value for [host_uri]: http://127.0.0.1:5000
What is the value for [username]: admin
Password for user admin:
[INFO] File does not exist, creating it.
[INFO] Credentials saved to: /root/.timesketch.token
dfTimewolf encountered one or more errors:
CRITICAL:   An unknown error occurred: 'NoneType' object has no attribute 'serialize'
Full traceback:
Traceback (most recent call last):
  File "/opt/dftimewolf/dftimewolf/lib/state.py", line 160, in _SetupModuleThread
    module.SetUp(**new_args)
  File "/opt/dftimewolf/dftimewolf/lib/exporters/timesketch.py", line 54, in SetUp
    self.timesketch_api = timesketch_utils.GetApiClient(self.state)
  File "/opt/dftimewolf/dftimewolf/lib/timesketch_utils.py", line 44, in GetApiClient
    ts_client.credentials, config_assistant=assistant)
  File "/opt/dftimewolf/venv/lib64/python3.6/site-packages/timesketch_api_client/crypto.py", line 257, in save_credentials
    data = cred_obj.serialize()
AttributeError: 'NoneType' object has no attribute 'serialize'

Critical error found. Aborting.

\
\
\

If I ignore this error and I try to run the recipe again, i am getting a different, wrong credential error.
\
\
\

Configuration loaded from: /opt/dftimewolf/data/config.json
Loading recipe...
Loaded recipe plaso_ts with 3 modules
Running preflights...
Setting up modules...
dfTimewolf encountered one or more errors:
CRITICAL:   An unknown error occurred: Unable to decrypt data, password wrong? (error )
Full traceback:
Traceback (most recent call last):
  File "/opt/dftimewolf/venv/lib64/python3.6/site-packages/cryptography/fernet.py", line 104, in _verify_signature
    h.verify(data[-32:])
  File "/opt/dftimewolf/venv/lib64/python3.6/site-packages/cryptography/hazmat/primitives/hmac.py", line 66, in verify
    ctx.verify(signature)
  File "/opt/dftimewolf/venv/lib64/python3.6/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/dftimewolf/venv/lib64/python3.6/site-packages/timesketch_api_client/crypto.py", line 315, in load_credentials
    data_string = crypto.decrypt(data)
  File "/opt/dftimewolf/venv/lib64/python3.6/site-packages/cryptography/fernet.py", line 75, in decrypt
    return self._decrypt_data(data, timestamp, ttl)
  File "/opt/dftimewolf/venv/lib64/python3.6/site-packages/cryptography/fernet.py", line 117, in _decrypt_data
    self._verify_signature(data)
  File "/opt/dftimewolf/venv/lib64/python3.6/site-packages/cryptography/fernet.py", line 106, in _verify_signature
    raise InvalidToken
cryptography.fernet.InvalidToken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/dftimewolf/dftimewolf/lib/state.py", line 160, in _SetupModuleThread
    module.SetUp(**new_args)
  File "/opt/dftimewolf/dftimewolf/lib/exporters/timesketch.py", line 54, in SetUp
    self.timesketch_api = timesketch_utils.GetApiClient(self.state)
  File "/opt/dftimewolf/dftimewolf/lib/timesketch_utils.py", line 38, in GetApiClient
    config.configure_missing_parameters(config_assistant=assistant)
  File "/opt/dftimewolf/venv/lib64/python3.6/site-packages/timesketch_api_client/config.py", line 76, in configure_missing_parameters
    config_assistant=config_assistant, password=token_password)
  File "/opt/dftimewolf/venv/lib64/python3.6/site-packages/timesketch_api_client/crypto.py", line 323, in load_credentials
    '{0!s})'.format(e))
OSError: Unable to decrypt data, password wrong? (error )

So, I think, the **.timesketch.token** was not properly generated.

**Comment by kiddinn** [comment] 2020-05-15 18:43
I'll take a closer look at this.

So you are authenticating to TS using `timesketch` auth, that is user/pass, not OAUTH?

I'll test this again on my side, this may be an issue on TS side, not wolf, but I'll need to test this a bit more.

Can you delete `~/.timesketch.token` and test again to see if it is the same?

Also can you double check your ~/.timesketchrc` file to see whether it has a `cred_key` entry (just double check whether that entry exists)

**Comment by kiddinn** [comment] 2020-05-15 18:44
Can you remove the `cred_key` entry from the RC file and delete the `~/.timesketch.token` file and test again?

**Comment by kiddinn** [comment] 2020-05-15 18:52
is it possible you entered the wrong password?

if so, then delete the .token file and try again, I'll test that scenario and make sure a fix is put in place, that is a check is made to see whether the code is properly authenticated.

**Comment by knsankar** [comment] 2020-05-15 19:00
I had same doubts earlier. So, I checked my credential again logging-in gui and it works fine.
Also, I removed .timesketchrc file and .timesketch.token files and tried several times and got the same error.

and I use auth_mode = timesketch

**Comment by knsankar** [comment] 2020-05-15 19:07
Here is my rcfile contents

host_uri = http://127.0.0.1:5000
username = admin
verify = True
client_id =
client_secret =
auth_mode = timesketch
cred_key = <some base64 value>


I reconfigured with fqdn as host_uri.

**Comment by kiddinn** [comment] 2020-05-20 09:52
sorry for the late reply, but I wanted to ask one more qq ... 

can you test the `timesketch_importer.py` tool to see if that is the same behavior?

`timesketch_importer.py --sketch_id ID path_to_file_to_upload`

**Comment by knsankar** [comment] 2020-05-20 12:25
`timesketch_importer.py` is working fine.

#python /opt/dftimewolf/venv/bin/timesketch_importer.py --sketch_id 25 /tmp/tmpr9c8zdrf/2d1c69396b2f48c3a23f275ba0fddd9a.plaso
Password for user admin:
INFO:crypto_client_api:File does not exist, creating it.
INFO:crypto_client_api:Credentials saved to: /root/.timesketch.token
INFO:timesketch_importer:Creating a client.
INFO:timesketch_importer:Client created.
INFO:timesketch_importer:Saving TS config.
What is the timeline name [2d1c69396b2f48c3a23f275ba0fddd9a]:
INFO:timesketch_importer:Uploading file.
INFO:timesketch_importer:File got successfully uploaded to sketch: 25

**Comment by kiddinn** [comment] 2020-06-04 21:07
is this still an issue?

Wondering whether you can update to the latest version and tell me whether this is still an issue, if so, then I'll add some debugging for us to figure this out, since I have a hard time to reproduce this.

**Comment by Fryyyyy** [comment] 2020-06-30 01:15
I believe this is still an issue, as I am experiencing it

**Comment by knsankar** [comment] 2020-07-02 19:31
Hi @kiddinn 

Sorry for the delay. I was out of office.

I pulled the dftimewolf repo and updated my existing install.

my commit hash:
```
# git rev-parse HEAD
93e240e1bb2ca6969d3c2211d7b276e29a466316
```

I got this following error when I try to use _grr_artifact_ts_ recipe 
```
Recipe data path: /opt/dftimewolf/data
Configuration loaded from: /opt/dftimewolf/data/config.json
Loading recipe...
Loaded recipe grr_artifact_ts with 3 modules
Running preflights...
Setting up modules...
dfTimewolf encountered one or more errors:
CRITICAL:   An unknown error occurred: 'NoneType' object has no attribute 'serialize'
Full traceback:
Traceback (most recent call last):
  File "/opt/dftimewolf/dftimewolf/lib/state.py", line 162, in _SetupModuleThread
    module.SetUp(**new_args)
  File "/opt/dftimewolf/dftimewolf/lib/exporters/timesketch.py", line 51, in SetUp
    self.timesketch_api = timesketch_utils.GetApiClient(self.state)
  File "/opt/dftimewolf/dftimewolf/lib/timesketch_utils.py", line 42, in GetApiClient
    ts_client.credentials, config_assistant=assistant)
  File "/opt/dftimewolf_venv/venv/lib64/python3.6/site-packages/timesketch_api_client/crypto.py", line 114, in save_credentials
    data = cred_obj.serialize()
AttributeError: 'NoneType' object has no attribute 'serialize'

Critical error found. Aborting.
```

**Comment by knsankar** [comment] 2020-07-06 08:08
Also, when I setup the credential with `timesketch_importer.py` , it properly generates ~/.timesketch.token and works. After that, when I try to run `dftimewolf grr_artifact_ts` it throws the error mentioned in https://github.com/log2timeline/dftimewolf/issues/276#issuecomment-653184709 and messes up the timesketch.token file. So, if I try to run the `timesketch_importer.py` again it throws credential error. I have to remove and regenerate timesketch.token again to use it.

**Comment by kiddinn** [comment] 2020-07-06 13:19
Once https://github.com/google/timesketch/pull/1288 has been merged and pushed to pypi, then I'll ask if you can test the code against this PR to see if it is fixed.

**Comment by knsankar** [comment] 2020-07-07 08:56
Hi @kiddinn 
The PR seems to be merged. But this issue is still persists.

**Comment by kiddinn** [comment] 2020-07-07 09:27
ok, so the TS PR has been merged, but not the timewolf one.

**Comment by kiddinn** [comment] 2020-07-07 09:44
ok, the dftimewolf PR has been merged now. Can you test now, update everything.

You'll need to update the TS import/api client as well (use the versions in requirements.txt)

**Comment by knsankar** [comment] 2020-07-08 07:49
Hi @kiddinn 

The issue is fixed now. Thanks :)

**Comment by kiddinn** [comment] 2020-07-08 12:13
great... thank you for confirming

**Closed by kiddinn** 2020-07-08 12:13 UTC
Labels: bug
